### PR TITLE
Small update for button Configuration Zwave

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by gerard33 — CHANGES_REQUESTED** [review]
Thanks for your updates!

However I don't agree with this change. This would mean that the ZWave button is not red anymore during the initialization but has the same color as the normal button. So you can't see if Zwave is still initializing or if it's ready yet.

**Review by gerard33 — CHANGES_REQUESTED** [review]
That's a good idea.

But please place the cursor: pointer; code just after this line: https://github.com/gerard33/dark-th3me/blob/master/dark-th3me/custom.css#L697

Then all code regarding this buttons is at the same place.

**Review by gerard33 — CHANGES_REQUESTED** [review]
See my previous comment, this part of the code can be removed.

**Review by gerard33 — CHANGES_REQUESTED** [review]
Same point as earlier: these buttons have a different color on purpose. So I don't want to change the color of these buttons to the default button color.

**Review by gerard33 — CHANGES_REQUESTED** [review]
See my earlier comments.

**Review by gerard33 — CHANGES_REQUESTED** [review]
The 'sub-tabs > .active > a:hover' has a yellow hover color on purpose. I choose to have another hover color then the active color.
I know on a iPad the hover color is shown also for an active button, but I normally use a desktop so that's no problem for me.

**Review by gerard33 — CHANGES_REQUESTED** [review]
The btn-danger has a correct border here. Changing it to 2px doesn't match with the other buttons.
Can you show me with a picture old and new what you are trying to achieve?

**Comment by ghost** [comment]
Screen for button Configuration for ZWAVE.
When i turn off and then turn ON OpenZwave module is initialized. When is initialized is RED
1zwave

After initialized OK is the same as other buttons:
2zwave

**Comment by ghost** [comment]
For cursor: pointer
I want only add cursoir pointer only for ACTIVE tabs. To be cursor "hand" for inactive tabs but cursor point for Active tab.

**Comment by ghost** [comment]
settings

**Comment by ghost** [comment]
buttons

**Comment by gerard33** [comment]
Did not find the time to have a look at this, but will still do that.

In general; I gave some buttons (alert, danger etc.) a different color on purpose, that's just as it is in the default theme. I am not going to change those to the default button color, but of course you are free to do that in your on fork :-)

**Comment by ghost** [comment]
margin

**Comment by gerard33** [comment]
I have implemented the agreed changes from this pull request in the custom.css file. There are also some changed which I disagree, so I will not merge the total pull request.
Thanks again for your input and your understanding :)

**Comment by pepeEL** [comment]
But why you dont accept changes for button CONFIG Zwave ?

**Pull request closed without merging**
